/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode

import adventofcode.dayone.TrebuchetCalibration

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    val trebuchetCalibration: TrebuchetCalibration = TrebuchetCalibration()
    val inputList: MutableList<String> = mutableListOf()
    App::class.java.getResource("/trebuchetCalibrationInput.txt")?.openStream()?.bufferedReader()?.lines()?.forEach({inputList.add(it)})
    val result = trebuchetCalibration.process(inputList.toList())
    println("Day 1 - Trebuchet Calibration: $result")
}
